version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_drop
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    privileged: true
    user: root
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      ENVIRONMENT: debug
      DB_HOST: db_drop
      DB_NAME: sky_drop
      DB_USER: root
      DB_PASS: test
    working_dir: /var/www/dropshipping
    networks:
      - app-network
    volumes:
      - .:/var/www/dropshipping/
      - .html:/var/www/html/
      - .docker/app/data:/var/storage

  #MySQL Service
  db:
    image: mysql:8.0
    container_name: db_drop
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sky_drop
      MYSQL_ROOT_PASSWORD: test
    networks:
      - app-network
    volumes:
      - .docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db_drop
      PMA_USER: root
      PMA_PASSWORD: test
    ports:
      - "8081:8080"

#  adminer:
#    image: adminer
#    restart: always
#    environment:
#      ADMINER_DESIGN: haeckel
#    networks:
#      - app-network
#    ports:
#      - 8081:8080

#  rabbit:
#    image: "rabbitmq:3-management"
#    hostname: "rabbit"
#    environment:
#      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
#      RABBITMQ_DEFAULT_USER: "rabbitmq"
#      RABBITMQ_DEFAULT_PASS: "rabbitmq"
#      RABBITMQ_DEFAULT_VHOST: "/"
#    networks:
#      - app-network
#    ports:
#      - "15672:15672"
#      - "5672:5672"

  #ElasticSearch
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
#    container_name: elasticsearch_sky
#    environment:
#      - node.name=elasticsearch
#      - node.master=true
#      - node.data=true
#      - node.ingest=false
#      - network.host=0.0.0.0
#      - network.bind_host=0.0.0.0
#      - cluster.name=docker-cluster
#      - cluster.initial_master_nodes=elasticsearch_sky
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - http.cors.enabled=true
#      - http.cors.allow-origin=*
#      - network.host=_eth0_
#    ulimits:
#      nproc: 65535
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./.docker/elasticsearch-data:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
#    networks:
#      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
